name = "orbixaibackend"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
ALLOWED_ORIGIN = "https://orbixai.ir,https://www.orbixai.ir,https://orbixai.moneymaker-media24.workers.dev,http://localhost:3000"

[[d1_databases]]
binding = "DB"
database_name = "orbixai-db"
database_id = "bce48b63-2e56-4e19-b611-5e612b4e7725"